config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

root 'home#welcome'

resources :places, only: [:index] do
  resources :trips, only: [:index]
end

resources :activities, only: [:index] do
  resources :trips, only: [:index]
end

resources :trips, only: [:new, :create, :edit, :update, :destroy]

resources :trips, only: [:show] do
  resources :participations, only: [:create]
end

resources :profiles, only: [:edit, :update, :show] do resources :reviews, only: [:index, :new, :create, :edit, :update, :destroy]
end

get '/places/:place_id/trips/calendar' => 'trips#calendar'
get '/activities/:activity_id/trips/calendar' => 'trips#calendar'

post 'search' => 'search#create'

get 'confirm_joiner/:id' => 'participations#add_joiner'

get 'my_trips' => 'home#my_trips'
get 'my_pending_trips' => 'home#my_pending_trips'

get 'filter_activities/:category' => 'activities#filter'

end

app/models/trip.rb
class Trip < ActiveRecord::Base
	belongs_to :place
	belongs_to :activity
	belongs_to :user
	has_many :users, through: :participation

	validates :organizer, presence: true
	validates :place_id, presence: true
	validates :activity_id, presence: true
	validates :from_date, presence: true
	validates :to_date, presence: true
	validates :description, presence: true
	validates :capacity, numericality: { only_integer: true, greater_than_or_equal_to: 1 }, allow_blank: true

	validate :from_date_is_in_future
	validate :from_date_before_to_date
	# validate :no_duplicates

	# def no_duplicates
	# 	Trip.all.each do |trip|
	# 		check here all attributes
	# 	end
	# end

  def create_participation current_user
    Participation.create user_id: current_user.id, trip_id: id, confirmed: true
  end

	def from_date_is_in_future
		if from_date == nil
			return
		elsif Date.today > from_date
			errors.add(:from_date, "should be in the future")
		end
	end

	def from_date_before_to_date
		if from_date == nil
			return
		elsif from_date > to_date
			errors.add(:to_date, "should be after its beginning")
		end
	end

	def reviewable? current_user
		if has_passed && (if_participant? current_user)
			@can_review
		else
			[]
		end
	end

	def joinable? current_user
		return true if capacity.nil?

		get_count_of_people
		current_trip_size = @count[:confirmed_people]
		if (if_participant? current_user) || (capacity == current_trip_size)
			false
		else
			true
		end
	end

	def get_count_of_people
		@count = {}
		@count[:pending_people] = (get_trip_participants false).length
		@count[:confirmed_people] = (get_trip_participants true).length
		@count
	end

	def has_passed
		to_date < Date.today
		# Date.today <= Date.today+1
	end

	def if_participant? current_user
		get_trip_participants true
		@can_review.include? current_user.id
	end

	def get_trip_participants status
		@participations = Participation.where(trip_id: self.id, confirmed: status)
		@can_review = []
		@participations.each do |p|
			@can_review << p.user_id
		end
		(@can_review.uniq! == nil) ? @can_review : @can_review.uniq!
	end

	def self.update_trip (params, trip_id, organizer_id)
		trip = Trip.find(trip_id)
		trip.save_trip_info(params, organizer_id)
		trip
	end

	def self.create_new_trip (params, organizer_id)
		trip = Trip.new
		trip.save_trip_info(params, organizer_id)
		trip
	end

	def save_trip_info(params, organizer_id)
		self.place_id = check_place params["place"]
		activity =
			if (params["activity_create"] == "")
				params["activity"]
			else
				params["activity_create"]
			end

		self.activity_id = check_activity activity
		self.organizer = organizer_id
		self.from_date = params["from_date"]
		self.to_date = params["to_date"]
		self.capacity = params["capacity"]
		self.description = params["description"]
	end

	def name
		"#{activity.activity_name} in #{place.city}"
	end

	private

	def check_place city
		city.capitalize!
		current_place = Place.where(city: city)
		if current_place.exists?
			current_place[0].id
		else
			new_place = Place.create(city: city)
			new_place.id
		end
	end

	def check_activity activity
		activity = activity.capitalize
		current_activity = Activity.where(activity_name: activity)
		if current_activity.exists?
			current_activity[0].id
		else
			new_activity = Activity.create(activity_name: activity, category: "Others")
			new_activity.id
		end
	end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
	respond_to :json, :html

	before_action :authenticate_user!, except: [:index]

	def index
		 @search = Search.new
		if params[:place_id]
			place = Place.find(params[:place_id])
			@trips = Trip.where(place_id: place.id).all
			@link = '/places/'+params[:place_id]+'/trips/calendar'
		elsif params[:activity_id]
			activity= Activity.find(params[:activity_id])
			@trips = Trip.where(activity_id: activity.id).all
			@link = '/activities/'+params[:activity_id]+'/trips/calendar'
		end
	end

	def calendar
		@search = Search.new
		if params[:place_id]
			place = Place.find(params[:place_id])
			@trips = Trip.where(place_id: place.id).all
		elsif params[:activity_id]
			activity= Activity.find(params[:activity_id])
			@trips = Trip.where(activity_id: activity.id).all
		end
	end

	def show
		@search = Search.new
		@trip = Trip.find(params[:id])
	end

	def new
		@search = Search.new
		@trip = Trip.new
		@activities = Activity.all
		# @categories = Activity.categories
		# @categories << "All"
		# @categories.sort!
	end

	def create
		@activities = Activity.all.limit(10)
		organizer_id = current_user.id
		@trip = Trip.create_new_trip(trip_params, organizer_id)
			if @trip.save
				@trip.create_participation current_user
				flash[:success] = "Trip has been created!"
				redirect_to action: 'show', id: @trip.id
			else
			@errors = @trip.errors.full_messages
			flash[:error] = @errors.first
			redirect_to action: 'new'
			end
	end

	def edit #only if current_user = organizer
		@search = Search.new
		@trip = Trip.find(params[:id])
		@activities = Activity.all.limit(10)
		if @trip.organizer == current_user.id
			@place = @trip.place.city
			@activity = @trip.activity.activity_name
			render 'edit'
		else
			flash[:error] = "Sorry you are not the organizer of this trip."
			redirect_to action: 'show', id: @trip.id
		end
	end

	def update
		@activities = Activity.all.limit(10)
		organizer_id = current_user.id
		@trip = Trip.update_trip(trip_params, params[:id], organizer_id)
		if @trip.save
				flash[:success] = "Trip updated!"
				redirect_to	action: 'show', id: @trip.id
		else
			@errors	=	@trip.errors.full_messages
			flash[:error] = @errors.first
			render 'edit'
		end
	end

	def destroy
		@trip = Trip.find(params[:id])
		Participation.destroy_all(trip_id: @trip.id)
		@trip.destroy
		flash[:success] = "Trip has been cancelled!"
		redirect_to action: 'index', controller: 'places'
	end

private

	def trip_params
		params.require(:trip).permit(:place, :activity, :activity_create, :from_date, :to_date, :capacity, :description)
	end

end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/calendar.html.erb
 <div id='calendar'></div>

app/views/trips/edit.html.erb
<h1><%= @trip.name %></h1>

<%= render '/shared/formtrips' %>

app/views/trips/index.html.erb
<ul class="spec_bar">
  <li class='calendar_button'><%=link_to "Calendar view", @link, method: 'get' %></li>
  <li><%=link_to "Create a new trip", new_trip_path%></li>
  <li><%=link_to "See other places", places_path %></li>
</ul>

<div class="trips_container">
  <% unless @trips == nil %>
    <% @trips.each do |trip| %>
    <div class="trip_card">
<!--       <% if trip.to_date < Date.today %>
        <div class="ribbon-wrapper">
          <div class="ribbon">COMPLETED</div>
        </div>
      <% end %> -->
      <img class="trip_image" src="https://raw.github.com/Magnus-G/Random/master/mountains.png" alt="">
      <div class="trip_text">
        <div class="trip_title">
          <%=link_to trip.name, trip_path(:id => trip.id)%>
        </div>
      <table class="trip_info">
        <tbody>
          <tr>
            <td colspan='2'><%= trip.description %></td>
          </tr>
          <tr>
            <th>Starting on:</th>
            <td><%= trip.from_date %></td>
          </tr>
          <tr>
            <th>Until:</th>
            <td><%= trip.to_date %></td>
          </tr>
        </tbody>
      </table>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/trips/new.html.erb
<h1> Create your own trip! </h1>

<%= render '/shared/formtrips' %>

app/views/trips/show.html.erb
<ul class="spec_bar">
  <li class='calendar_button'>
    <% if @trip.joinable? current_user %>
      <%=link_to "Join this trip", trip_participations_path(:trip_id => @trip.id), method: 'post' %>
      <% else %>
        <span class='fulltrip'>CANNOT JOIN</span><% flash[:notice] = "Sorry this trip is full!" %>
      <% end %>
  </li>
  <% if @trip.organizer == current_user.id %>
  <li>
    <%=link_to "Edit this trip", edit_trip_path(@trip.id) %>
  </li>
  <li><%=link_to "Cancel this trip", trip_path(@trip.id), method: 'delete', confirm: 'Are you sure?' %>
  </li>
  <% else %>
    <li id='colspan2'><%=link_to "See other trips in the same place", place_trips_path(@trip.place_id) %></li>
  <% end %>
</ul>

<div class='trip_display'>
  <h1><span class='trip_name'><%= @trip.name %></span></h1>

<div class='trip_info_on_show'>
<div><span class="trip_text_on_show ">Organized by:</span> <h4><%= link_to User.find(@trip.organizer).username, profile_path(:id => Profile.where(user_id: @trip.organizer).first.user_id) %></h4></<div>
<div><span class="trip_text_on_show  block_it">From Date:</span> <h4><%= @trip.from_date %></h4></div>
<div><span class="trip_text_on_show  block_it">To Date:</span> <h4><%= @trip.to_date %></h4><br></div>
<div><span class="trip_text_on_show  block_it">Capacity: </span><h4><%= @trip.capacity %></h4></div>
<div><p><span class="
.trip_text_on_show "><%= @trip.description %></span></p></div>
</div>

<div class='trip_status'>
  <span class="trip_text_on_show"><h2>Status</h2></span>
  <% count = @trip.get_count_of_people %>
  <div><span class="trip_text_on_show">Pending:</span><h4><%= count[:pending_people] %></h4></div>
  <div><span class="trip_text_on_show">Confirmed:</span><h4><%= count[:confirmed_people] %></h4></div>
</div>

<div class='reviewables'>
  <% review_members = @trip.reviewable? current_user %>
  <% if review_members.length >= 2 %>
  <span class="trip_text_on_show"><h2>Review your tripmates:</h2></span>
    <% review_members.each do |profile| %>
      <% if profile != current_user.id %>
        <ul>
        <li><%=link_to User.find(profile).username, new_profile_review_path(:profile_id => Profile.where(user_id: profile).first) %></li>
        </ul>
       <% end %>
    <% end %>
  <% end %>
</div>