config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

root 'home#welcome'

resources :places, only: [:index] do
  resources :trips, only: [:index]
end

resources :activities, only: [:index] do
  resources :trips, only: [:index]
end

resources :trips, only: [:new, :create, :edit, :update, :destroy]

resources :trips, only: [:show] do
  resources :participations, only: [:create]
end

resources :profiles, only: [:edit, :update, :show] do resources :reviews, only: [:index, :new, :create, :edit, :update, :destroy]
end

get '/places/:place_id/trips/calendar' => 'trips#calendar'
get '/activities/:activity_id/trips/calendar' => 'trips#calendar'

post 'search' => 'search#create'

get 'confirm_joiner/:id' => 'participations#add_joiner'

get 'my_trips' => 'home#my_trips'
get 'my_pending_trips' => 'home#my_pending_trips'

get 'filter_activities/:category' => 'activities#filter'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def welcome
    @search = Search.new
  end

  def my_trips
    @search = Search.new
    @trips = Trip.where(organizer: current_user.id)
    if @trips == nil
      flash[:notice] = "You don't have any trips yet! Why not create one?"
    else
      @trips
    end
    render 'mytrips'
  end

  def my_pending_trips
    @search = Search.new
    trips = Trip.where(organizer: current_user.id)
    @trips = []
    trips.each do |trip|
      if trip.to_date > Date.today
        @trips << trip
      end
    end

    if @trips == nil
      flash[:notice] = "You don't have any pending trips! Why not create a new one?"
    else
      @trips
    end
    render 'mytrips'
  end

end

app/views/home/mytrips.html.erb
<ul class="spec_bar">
  <li><%=link_to "Show only pending trips", my_pending_trips_path, method: 'get', :style=>"padding: 15px 20px" %></li>
  <li><%=link_to "Create a new trip", new_trip_path%></li>
  <li><%=link_to "See other places", places_path %></li>
</ul>

<div class="trips_container">
  <% unless @trips == nil %>
    <% @trips.each do |trip| %>
    <div class="trip_card">
      <% if trip.to_date < Date.today %>
        <div class="ribbon-wrapper">
          <div class="ribbon">COMPLETED</div>
        </div>
      <% end %>
      <img class="trip_image" src="https://raw.github.com/Magnus-G/Random/master/mountains.png" alt="">
      <div class="trip_text">
        <div class="trip_title">
          <%=link_to trip.name, trip_path(:id => trip.id)%>
        </div>
      <table class="trip_info">
        <tbody>
          <tr>
            <td colspan='2'><%= trip.description %></td>
          </tr>
          <tr>
            <th>Starting on:</th>
            <td><%= trip.from_date %></td>
          </tr>
          <tr>
            <th>Until:</th>
            <td><%= trip.to_date %></td>
          </tr>
        </tbody>
      </table>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/home/welcome.html.erb
<div class='main'>
  <%= image_tag("logo_white_text.png") %>
  <h1>Find companions for your next trip!</h1>
</div>