config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

root 'home#welcome'

resources :places, only: [:index] do
  resources :trips, only: [:index]
end

resources :activities, only: [:index] do
  resources :trips, only: [:index]
end

resources :trips, only: [:new, :create, :edit, :update, :destroy]

resources :trips, only: [:show] do
  resources :participations, only: [:create]
end

resources :profiles, only: [:edit, :update, :show] do resources :reviews, only: [:index, :new, :create, :edit, :update, :destroy]
end

get '/places/:place_id/trips/calendar' => 'trips#calendar'
get '/activities/:activity_id/trips/calendar' => 'trips#calendar'

post 'search' => 'search#create'

get 'confirm_joiner/:id' => 'participations#add_joiner'

get 'my_trips' => 'home#my_trips'
get 'my_pending_trips' => 'home#my_pending_trips'

get 'filter_activities/:category' => 'activities#filter'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	has_many :places, through: :trips

	validates :activity_name, presence: true,uniqueness: {case_sensitive: false}

  def self.categories
    @category_list = []
    all_activities = self.all
    all_activities.each do |activity|
      @category_list << activity.category
    end
    @category_list.uniq! == nil ? @category_list : @category_list.uniq!
    @category_list
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def index
    @activities = Activity.all.limit(10)
    @search = Search.new
  end

  def filter
    if params[:category] == "All"
      @activities = Activity.all
    else
      @activities = Activity.where(category: params[:category])
    end
  end

end

app/views/activities/index.html.erb
<ul class="spec_bar">
  <li class='current_spec'>ACTIVITIES</li>
  <li><%=link_to "Create a new trip", new_trip_path%></li>
  <li><%=link_to "See other places", places_path %></li>
</ul>

<h1>What do you want to do?</h1>
<p>Click on the activities to see all the trips!</p>
<ul class='index_list'>
  <% @activities.each do |activity| %>
  <li class='index_item'>
    <%= link_to image_tag("#{activity.activity_name}.png"), activity_trips_path(activity.id) %>
    <label class='index_item_label'>
    <%= link_to activity.activity_name, activity_trips_path(activity.id) %>
    </label>
    </li>
  <% end %>
</ul>