config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

root 'home#welcome'

resources :places, only: [:index] do
  resources :trips, only: [:index]
end

resources :activities, only: [:index] do
  resources :trips, only: [:index]
end

resources :trips, only: [:new, :create, :edit, :update, :destroy]

resources :trips, only: [:show] do
  resources :participations, only: [:create]
end

resources :profiles, only: [:edit, :update, :show] do resources :reviews, only: [:index, :new, :create, :edit, :update, :destroy]
end

get '/places/:place_id/trips/calendar' => 'trips#calendar'
get '/activities/:activity_id/trips/calendar' => 'trips#calendar'

post 'search' => 'search#create'

get 'confirm_joiner/:id' => 'participations#add_joiner'

get 'my_trips' => 'home#my_trips'
get 'my_pending_trips' => 'home#my_pending_trips'

get 'filter_activities/:category' => 'activities#filter'

end

app/views/refills/_accordion.html.erb
<ul class="accordion">
  <li = "accordion_first">
    <a href="javascript:void(0)" class="js-accordion-trigger">Browse</a>
    <ul class="submenu">
      <li><%= link_to "by City", places_path %></li>
      <li><%= link_to "by Activity", activities_path %></li>
    </ul>
  </li>
  <li class="accordion_first">
    <a href="javascript:void(0)" class="js-accordion-trigger">Search</a>
    <ul class="submenu">
      <li>
      <div class="search-bar">
        <div class="search-and-submit">
          <%= form_for @search do |f| %>
            <%= f.label "Find by city or activity", :class => "search_label" %>
            <%= f.text_field :keyword, type: "search", placeholder: "Enter search" %>
            <%= f.submit "Find me a trip!"%>
        </div>
      </div>
      <% end %>
      </li>
    </ul>
  </li>
  <% if user_signed_in? && current_user %>
  <li class="accordion_first">
    <a href="javascript:void(0)" class="js-accordion-trigger">Profile</a>
    <ul class="submenu">
      <li><%= link_to "View my profile", profile_path(id: Profile.where(user_id: current_user.id).first.id) %></li>
      <li><%= link_to "Edit my profile", edit_profile_path(id: Profile.where(user_id: current_user.id).first.id) %></li>
    </ul>
  </li>
  <li = "accordion_first">
    <a href="javascript:void(0)" class="js-accordion-trigger">Trips</a>
    <ul class="submenu">
      <li><%=link_to "Create a new trip", new_trip_path%></li>
      <li><%= link_to "View my trips", my_trips_path, method: 'get' %></li>
    </ul>
  </li>
  <% end %>
</ul>

<script>
  jQuery('.js-accordion-trigger') // find the trigger
    .bind('click', function(){
      jQuery(this).parent().find('.submenu').slideToggle('fast');  // apply the toggle to the ul
      jQuery(this).parent().toggleClass('is-expanded');
      event.preventDefault();
  });
</script>

app/views/refills/_cards.html.erb
<div class="cards">
<%if @trips != nil %>
<% @trips.each do |trip| %>
    <div class="card">
    <div class="card-image">
      <img src="https://raw.github.com/Magnus-G/Random/master/mountains.png" alt="">
    </div>

    <div class="card-header">
      <%=link_to trip.name, trip_path(:id => trip.id)%>
    </div>
    <div class="card-copy">
      <p><%= trip.description %></p>
    </div>
    <div class="card-stats">
      <ul>
        <li>From Date: <%= trip.from_date %></li>
        <li>To Date: <%= trip.to_date %></li>
        <!-- <li>923<span>Objects</span></li> -->
      </ul>
    </div>
    <% end %>
  </div>
    <% else %>
      <%= "Sorry no results found!" %>
      <% end %>

  <!-- <div class="card">
    <div class="ribbon-wrapper"><div class="ribbon">RIBBON</div></div>
    <div class="card-image">
      <img src="https://raw.github.com/Magnus-G/Random/master/mountains-4.png" alt="">
    </div>
    <div class="card-header">
      Another Card
    </div>
    <div class="card-copy">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga, officiis sunt neque facilis culpa molestiae necessitatibus delectus veniam provident.</p>
    </div>
    <div class="card-stats">
      <ul>
        <li>98<span>Items</span></li>
        <li>298<span>Things</span></li>
        <li>923<span>Objects</span></li>
      </ul>
    </div>
  </div>

  <div class="card">
    <div class="card-image">
      <img src="https://raw.github.com/Magnus-G/Random/master/mountains-3.png" alt="">
    </div>
    <div class="card-header">
      The Last Card
    </div>
    <div class="card-copy">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga, officiis sunt neque facilis culpa molestiae necessitatibus delectus veniam provident.</p>
    </div>
    <div class="card-stats">
      <ul>
        <li>98<span>Items</span></li>
        <li>298<span>Things</span></li>
        <li>923<span>Objects</span></li>
      </ul>
    </div>
  </div> -->
</div>

app/views/refills/_modal.html.erb
<div class="modal">
  <label for="modal-1">
    <div class="btn js-btn">Click for Modal</div>
  </label>
  <input class="modal-state" id="modal-1" type="checkbox" />
  <div class="modal-window">
    <div class="modal-inner">
      <label class="modal-close" for="modal-1"></label>
      <h1>Modal Title</h1>
      <p class="intro">Intro text lorem ipsum dolor sit ametm, quas, eaque facilis aliquid cupiditate tempora cumque ipsum accusantium illo modi commodi  minima.</p>
      <p class="body">Body text lorem ipsum dolor ipsum dolor sit sit possimus amet, consectetur adipisicing elit. Itaque, placeat, explicabo, veniam quos aperiam molestias eriam molestias molestiae suscipit ipsum enim quasi sit possimus quod atque nobis voluptas earum odit accusamus quibusdam.</p>
    </div>
  </div>
</div>

app/views/refills/_search-bar.html.erb
  <div class="search-bar">
    <div class="search-and-submit">
      <input type="search" placeholder="Enter Search" />
      <button type="submit">
        <img src="https://raw.githubusercontent.com/Magnus-G/Random/master/search-icon-black.png" alt="">
      </button>
    </div>
  </div>

app/views/refills/_switch.html.erb
<div class="switch-container">
  <input type="checkbox" id="switch-toggle-1" name="switch-toggle" class="switch-checkbox" checked/>
  <label class="switch-label" for="switch-toggle-1">
    <div class="switch-inner"></div>
    <div class="switch-toggle-switch"></div>
  </label>
</div>